title: "newsplace6 - Latest News"
description: "Stay updated with the latest news from around the world."
baseurl: "/"
url: "http://newsplace6.com"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
