title: "newsplace4 - Latest News"
description: "Stay updated with the latest news from around the world."
baseurl: "/"
url: "http://newsplace4.com"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
