title: "{{ site.name }} - Latest News"
description: "Stay updated with the latest news from around the world."
baseurl: "/"
url: "http://{{ site.name }}"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
